### ISSUE TITLE
Question re HNN model setup

### ISSUE THREAD

**Issue by pgleeson** [Neurosim-lab/netpyne_workspace#1]
@salvadord @joewgraham Quick question, regarding linking population to the cell rule/params. Previously I assumed you linked these via the matching conditions, e.g.
```
    netParams.popParams['PYR'] = {'cellModel': 'HH', 'cellType': 'PYR', 'numCells': pop_size} 

    # Cell parameters
    cellRule = {'conds': {'cellModel': 'HH', 'cellType': 'PYR'},  'secs': {}} 	# cell rule dict
    ...
    netParams.cellParams['PYR'] = cellRule  	
```

but there seems to be an implicit linking now between the populations and types in hnn:

https://github.com/Neurosim-lab/netpyne_workspace/blob/f6f50baa572f735ed2fa4c6c4b3ee7a7edd0a124/hnn_simple.py#L856

https://github.com/Neurosim-lab/netpyne_workspace/blob/f6f50baa572f735ed2fa4c6c4b3ee7a7edd0a124/hnn_simple.py#L588-L605

If there are no conds, does it just match by name?

**Comment by joewgraham** [comment]
Hi Padraig, yeah, in version 0.9.7 we made the 'conds' optional, and if they aren't there, we use the dict key as the 'cellType'.

**Comment by pgleeson** [comment]
Thnaks! Will use that convention in the neuroml export.
